### ISSUE TITLE
Game Cannot be found

### ISSUE THREAD

**Issue by MansiAyer** [neurek88/Bionic-Boar#1]
I can't find the game on Google play, is it still available or has it been removed?
If it is still available, could I please try the game out?

**Comment by neurek88** [comment]
Google play removed it because I didn't specify if it was a news app. Trying to get it back on play store.

**Comment by neurek88** [comment]
Should be live again. Thanks for letting me know. https://play.google.com/store/apps/details?id=com.TigerPaw.BionicBoar

**Comment by MansiAyer** [comment]
Thanks a lot!
